services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - net

  adat-api:
    restart: unless-stopped
    container_name: adat-api
    volumes:
      - ./dados_csv:/app/dados_csv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    networks:
      - net

volumes:
  redis_data:

networks:
  net:
    name: net-adat
    external: true
