version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env                 
  #   environment:
  #     - REDIS_ADDR=${REDIS_ADDR}
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_DB=${REDIS_DB}

volumes:
  redis_data: